### ISSUE TITLE
Use pathParams in expression

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/mashling#100]
The conditions expression in the tunable gateway example starts with `env.`. How can I make use of a path parameter in my condition? Basically I want to have one URL /{type}/{name} and use the type parameter to send the request to a specific handler. I tried setting the condition to `${pathParams.type == bla}` but that triggers an error saying condition expressions must start with trigger.content, trigger.header or env

**Comment by jpark800** [comment]
We don't have a pathParams support in the conditional expression currently. The http trigger's settings configuration can be used to select a specific handler for a path. To achieve that, there should be a separate http trigger definition for a different path in mashling configuration even though the same trigger instance could be used at runtime under the hood. There is an example at https://github.com/TIBCOSoftware/mashling-recipes/tree/master/recipes/rest-conditional-gateway.

**Comment by jeffreybozek** [comment]
@jpark800 @retgits The new v2 model of Mashling, which is now in the master branch, supports these kinds of expressions.
