### ISSUE TITLE
Error in Mashling CLI with latest flogo

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#108]
Getting the below error while installing Mashling with the latest Flogo version.

Command:
go get github.com/TIBCOSoftware/mashling/...

Error:
$ go get github.com/TIBCOSoftware/mashling/...
# github.com/TIBCOSoftware/mashling/cli/app
src\github.com\TIBCOSoftware\mashling\cli\app\api.go:196: cannot use SetupExistingProjectEnv(appDir) (type "github.com/TIBCOSoftware/mashling/cli/env".Project) as type "github.com/TIBCOSoftware/flogo-cli/env".Project in argument to "github.com/TIBCOSoftware/flogo-cli/app".BuildApp:
       "github.com/TIBCOSoftware/mashling/cli/env".Project does not implement "github.com/TIBCOSoftware/flogo-cli/env".Project (missing GetAppDir method)
src\github.com\TIBCOSoftware\mashling\cli\app\api.go:367: cannot use SetupExistingProjectEnv(appDir) (type "github.com/TIBCOSoftware/mashling/cli/env".Project) as type "github.com/TIBCOSoftware/flogo-cli/env".Project in argument to "github.com/TIBCOSoftware/flogo-cli/app".BuildApp:
       "github.com/TIBCOSoftware/mashling/cli/env".Project does not implement "github.com/TIBCOSoftware/flogo-cli/env".Project (missing GetAppDir method)
src\github.com\TIBCOSoftware\mashling\cli\app\api.go:1223: undefined: "github.com/TIBCOSoftware/flogo-cli/app".ExtractDependencies
src\github.com\TIBCOSoftware\mashling\cli\app\files.go:136: undefined: "github.com/TIBCOSoftware/flogo-cli/app".Dependency

**Comment by jpark800** [comment]
PR https://github.com/TIBCOSoftware/mashling/pull/109 resolves this issue.

**Comment by ykalidin** [comment]
Working Fine. Closing the issue.
