### ISSUE TITLE
Documentation and tutorials on writing recipes

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/mashling#115]
Can you please provide documentation and tutorial on how to write a mashling recipe?

**Comment by jpark800** [comment]
We are working on https://github.com/TIBCOSoftware/mashling/issues/122 to help with that.

**Comment by jpark800** [comment]
The tutorial based on V2 model is available at https://tibcosoftware.github.io/mashling/development/recipes/recipe_tutorial/
