### ISSUE TITLE
Tunables support in v2 model gateway

### ISSUE THREAD

**Issue by jpark800** [TIBCOSoftware/mashling#127]

**Comment by rameshpolishetti** [comment]
Tunable parameters can be passed to flogo flow using below syntax:

_"steps": [
    { 
		"service": "FlogoRestGetFlow",
		"input": {
  			"inputs.id": "${payload.pathParams.id}",
  			"inputs.endPoint": "http://petstore.swagger.io/v2/pet/:id"
		}
    }
]_

Complete working gateway.json is attached for reference.
[recipe_tunable_v2.json.txt](https://github.com/TIBCOSoftware/mashling/files/1874400/recipe_tunable_v2.json.txt)
