### ISSUE TITLE
CLI update for V2 model

### ISSUE THREAD

**Issue by jpark800** [TIBCOSoftware/mashling#130]

**Comment by jeffreybozek** [comment]
The [feature-v2-model](https://github.com/TIBCOSoftware/mashling/tree/feature-v2-model) branch accomplishes this.

**Comment by ykalidin** [comment]
All the commands in V1 have equivalent commands in V2.
The Build and list commands does not have any match which is obvious, closing the issue.

**Comment by ykalidin** [comment]
Updated commands in: http://confluence.tibco.com/display/engineering/V2+Model+Changes
