### ISSUE TITLE
Error if Put operation is called after Get operation in V2 Gateway.

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#145]
**Steps to reproduce:**
1)Start the gateway and hit the Get Service.
2)Hit the Put service. The gateway still searches for Pathparams instead of Content and fails.

Note: The same issue is observed if we hit the Put service first and then the Get service.

Used the below rest-conditional-gateway.json:
`{
  "mashling_schema": "1.0",
  "gateway": {
    "name": "MyProxy",
    "version": "1.0.0",
    "description": "This is a simple proxy.",
    "triggers": [
      {
        "name": "MyProxy",
        "description": "Animals rest trigger - PUT animal details",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "settings": {
          "port": "9096"
        },
        "handlers": [
          {
            "dispatch": "Pets",
            "settings": {
              "autoIdReply": "false",
              "method": "GET",
              "path": "/pets/{petId}",
              "useReplyHandler": "false"
            }
          },
          {
            "dispatch": "Pets1",
            "settings": {
              "autoIdReply": "false",
              "method": "PUT",
              "path": "/pets",
              "useReplyHandler": "false"
            }
          }
        ]
      }
    ],
    "dispatches": [
      {
        "name": "Pets",
        "routes": [
          {
            "steps": [
              {
                "service": "FlogoRestGetFlow",
                "input": {
                  "inputs.pathParams": "${payload.pathParams}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not available."
                }
              },
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body": "${FlogoRestGetFlow.response.outputs.data}"
                }
              }
            ]
          }
        ]
      },
      {
        "name": "Pets1",
        "routes": [
          {
            "if": "JSON.parse(payload.content.___copy___).name == 'SPARROW'",
            "steps": [
              {
                "service": "birds_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(birds_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(birds_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${birds_put.response.outputs.data}"
                }
              }
            ]
          },
          {
            "if": "JSON.parse(payload.content.___copy___).name == 'ELEPHANT' || JSON.parse(payload.content.___copy___).name == 'CAT'",
            "steps": [
              {
                "service": "mammals_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(mammals_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(mammals_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${mammals_put.response.outputs.data}"
                }
              }
            ]
          },
          {
            "steps": [
              {
                "service": "animals_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(animals_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(animals_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${animals_put.response.outputs.data}"
                }
              }
            ]
          }
        ]
      }
    ],
    "services": [
      {
        "name": "FlogoRestGetFlow",
        "description": "Make GET calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestGetActivity.json"
        }
      },
      {
        "name": "birds_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      },
      {
        "name": "mammals_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      },
      {
        "name": "animals_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      }
    ]
  }
}`

**Comment by jeffreybozek** [comment]
13d5cbbab3c3c79bea58e64fdeb87bf743955fdd resolves this issue by using the user provided 'reference' value instead of the definition provided 'ref' value as the key in the flow map.

**Comment by ykalidin** [comment]
Working fine with V2 Gateway Binary and V2 mashling.json . 
The issue still exists with V2 Gateway and V1 mashling.json .
Attaching the mashling.json used.
`{
  "mashling_schema": "0.2",
  "gateway": {
    "name": "demoRestGw",
    "version": "1.0.0",
    "display_name":"Content-based HTTP Router",
		"display_image":"displayImage.svg",
    "description": "A conditional HTTP router that routes requests based on content",
    "configurations": [
      {
        "name": "restConfig",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "description": "Configuration for rest trigger",
        "settings": {
          "port": "9096"
        }
      }
    ],
    "triggers": [
      {
        "name": "animals_rest_trigger",
        "description": "Animals rest trigger - PUT animal details",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "settings": {
          "config": "${configurations.restConfig}",
          "method": "PUT",
		      "path": "/pets",
          "optimize":"true"
        }
      },
      {
        "name": "get_animals_rest_trigger",
        "description": "Animals rest trigger - get animal details",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "settings": {
          "config": "${configurations.restConfig}",
          "method": "GET",
		      "path": "/pets/{petId}",
          "optimize":"true"
        }
      }
    ],
    "event_handlers": [
      {
        "name": "mammals_handler",
        "description": "Handle mammals",
        "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
      },
      {
        "name": "birds_handler",
        "description": "Handle birds",
        "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
      },
      {
        "name": "animals_handler",
        "description": "Handle other animals",
        "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
      },
      {
        "name": "animals_get_handler",
        "description": "Handle other animals",
        "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestGetActivity.json"
      }
    ],
    "event_links": [
      {
        "triggers": ["animals_rest_trigger"],
        "dispatches": [
          {
            "if": "${trigger.content.name in (ELEPHANT,CAT)}",
            "handler": "mammals_handler"
          },
          {
            "if": "${trigger.header.name == SPARROW}",
            "handler": "birds_handler"
          },
          {
            "handler": "animals_handler"
          }
        ]
      },
      {
        "triggers": ["get_animals_rest_trigger"],
        "dispatches": [
          {
            "handler": "animals_get_handler"
          }
        ]
      }
    ]
  }
}
`

**Comment by jpark800** [comment]
The issue occurs on V1 recipe and is a lower priority. Moved to the backlog.

**Comment by rameshpolishetti** [comment]
This issue is observed in V2 recipe as well.

**Comment by nareshkumarthota** [comment]
This issue occurs because of unique id creation during loading of action data. Same ID is getting created for different actions. Code part is available in **$GOPATH\src\github.com\TIBCOSoftware\mashling\vendor\github.com\TIBCOSoftware\flogo-contrib\action\flow\action.go** file Method Name: **createResource**, Line No 169.
If we provide a 1 nanosecond delay issue will get resolved.

**Comment by jeffreybozek** [comment]
This looks to be deprecated too. This will go away once we use a Mashling action instead of the flow action internally. Perhaps would should use Naresh's suggestion as a stopgap and just add a 1 ns delay in the current approach until the refactor is merged in?

**Comment by rameshpolishetti** [comment]
@jeffreybozek @nareshkumarthota Considering this method is deprecated and latest flogo version doesn't have this issue. My vote is - we can go with adding 1ns delay (in vendor/flogo/...) as a temporary fix.

**Comment by nareshkumarthota** [comment]
Fixed with PR #218
