### ISSUE TITLE
Error with Tracing in V2

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#146]
**Unknown type error:** is displayed while using the Tracing mashling jsons.

Run the attached json with the below command:
mashling-gateway-windows-amd64.exe -c rest-gateway-with-tracing.json

`{
  "mashling_schema": "1.0",
  "gateway": {
    "name": "MyProxy",
    "version": "1.0.0",
    "description": "This is a simple proxy.",
    "triggers": [
      {
        "name": "MyProxy",
        "description": "Animals rest trigger - PUT animal details",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "settings": {
          "port": "9096",
          "tracer": "zipkin",
          "tracerEndpoint": "http://localhost:9411/api/v1/spans"
        },
        "handlers": [
          {
            "dispatch": "Pets",
            "settings": {
              "autoIdReply": "false",
              "method": "GET",
              "path": "/pets/{petId}",
              "useReplyHandler": "false"
            }
          }
        ]
      }
    ],
    "dispatches": [
      {
        "name": "Pets",
        "routes": [
          {
            "steps": [
              {
                "service": "FlogoRestGetFlow",
                "input": {
                  "inputs.pathParams": "${payload.pathParams}",
                  "inputs.tracing": "${payload.tracing}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Failure"
                }
              },
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body": "${FlogoRestGetFlow.response.outputs.data}"
                }
              }
            ]
          }
        ]
      }
    ],
    "services": [
      {
        "name": "FlogoRestGetFlow",
        "description": "Make GET calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/Tracing.json"
        }
      }
    ]
  }
}`

**Comment by ykalidin** [comment]
The "Unknown type error:" is not seen if we update the Tracer activity Types in the Referenced Flogo.json.
**interface conversion: map[string]interface {} is not context.Context: missing method Deadline**
The above error is still seen for tracing recipes.

**Comment by jeffreybozek** [comment]
Commit 9906d9fbd115fa24f5c3b23143a245985d687945 should resolve this issue. Using the attached Mashling configuration produces no errors around interface conversions.

[Tracing.txt](https://github.com/TIBCOSoftware/mashling/files/1885531/Tracing.txt)

**Comment by ykalidin** [comment]
Working Fine.
