### ISSUE TITLE
Using Make on Windows machines

### ISSUE THREAD

**Issue by retgits** [TIBCOSoftware/mashling#152]
Using Make on a Windows machine isn't the best idea from a developer experience point of view. Looking at the contents of the Make file it might be a better idea to use a `go` file to execute those commands or leverage [Mage](https://github.com/magefile/mage)

Also, the statement that `Windows users can execute above commands as is using git-bash terminal.` is not entirely correct as the latest versions of Git for Windows no longer ship with Make.

**Comment by jeffreybozek** [comment]
@retgits The next release will begin to address this by providing pre-built binaries and running custom gateway build commands through a docker image that has everything pre-configured correctly. We are also looking at, eventually, converting the Makefile contents to a go file.

You can see details on the pre-built binaries for v2 [here](https://github.com/TIBCOSoftware/mashling/tree/feature-v2-model#installation-and-usage), the customized binary building [here](https://github.com/TIBCOSoftware/mashling/blob/feature-v2-model/docs/cli/README.md#create), and using Docker directly to build this project on your own [here](https://github.com/TIBCOSoftware/mashling/tree/feature-v2-model#using-docker).

**Comment by rameshpolishetti** [comment]
This is addressed with the PR #163
