### ISSUE TITLE
Header condition failing for V2 Json using V2 gateway binary.

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#158]
The  "if": "payload.header.name == 'test'", is always failing ,even if we pass header "name" as "test".Below is the json:
`{
  "mashling_schema": "1.0",
  "gateway": {
    "name": "MyProxy",
    "version": "1.0.0",
    "description": "This is a simple proxy.",
    "triggers": [
      {
        "name": "MyProxy",
        "description": "Animals rest trigger - PUT animal details",
        "type": "github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger",
        "settings": {
          "port": "9096"
        },
        "handlers": [
          {
            "dispatch": "Pets",
            "settings": {
              "autoIdReply": "false",
              "method": "GET",
              "path": "/pets/{petId}",
              "useReplyHandler": "false"
            }
          },
          {
            "dispatch": "Pets1",
            "settings": {
              "autoIdReply": "false",
              "method": "PUT",
              "path": "/pets",
              "useReplyHandler": "false"
            }
          }
        ]
      }
    ],
    "dispatches": [
      {
        "name": "Pets",
        "routes": [
          {
            "steps": [
              {
                "service": "FlogoRestGetFlow",
                "input": {
                  "inputs.pathParams": "${payload.pathParams}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not available."
                }
              },
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body": "${FlogoRestGetFlow.response.outputs.data}"
                }
              }
            ]
          }
        ]
      },
      {
        "name": "Pets1",
        "routes": [
          {
            "if": "payload.content.name == 'SPARROW'",
            "steps": [
              {
                "service": "birds_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(birds_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(birds_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${birds_put.response.outputs.data}"
                }
              }
            ]
          },
          { 
            "if": "payload.header.name == 'test'",
            "steps": [
              {
                "service": "mammals_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(mammals_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(mammals_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${mammals_put.response.outputs.data}"
                }
              }
            ]
          },
          {
            "steps": [
              {
                "service": "animals_put",
                "input": {
                  "inputs.content": "${payload.content}"
                }
              }
            ],
            "responses": [
              {
                "if": "JSON.parse(animals_put.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not added."
                }
              },
              {
                "if": "JSON.parse(animals_put.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body.pet": "${animals_put.response.outputs.data}"
                }
              }
            ]
          }
        ]
      }
    ],
    "services": [
      {
        "name": "FlogoRestGetFlow",
        "description": "Make GET calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestGetActivity.json"
        }
      },
      {
        "name": "birds_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      },
      {
        "name": "mammals_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      },
      {
        "name": "animals_put",
        "description": "Make PUT calls against a remote HTTP service using a Flogo flow.",
        "type": "flogoFlow",
        "settings": {
          "reference": "github.com/TIBCOSoftware/mashling/lib/flow/RestTriggerToRestPutActivity.json"
        }
      }
    ]
  }
}`

**Comment by jeffreybozek** [comment]
@rameshpolishetti @ykalidin I think this is due to the header names being converted by either the HTTP client or by the incoming http.Request in the mix trigger? When I pass the header 'name' with a value of 'test' I can see the incoming payload from the HTTP trigger with 'Name' as a key in the header parameters.

**Comment by rameshpolishetti** [comment]
@jeffreybozek @ykalidin - from my observation http.Request is being modified by underlying http stack. I also observed that http stack implementation varies between GO, NODE, etc..

I created simple HTTP listener using GO & nodejs to display http request header information. here is the outcome:

**http reqeust**:
curl -H "key-sample:value" -X GET localhost:8080

**headers log using GO based http listener** : 
Content-Length :  [16]
Content-Type :  [application/x-www-form-urlencoded]
User-Agent :  [curl/7.54.0]
Accept :  [*/*]
Name :  [VALUE]
Key-Sample :  [value]

**headers log using NODEJS based http listener**:
{
"host":"localhost:8080","user-agent":"curl/7.54.0","accept":"*/*","**key-sample":"value"**,"content-length":"16","content-type":"application/x-www-form-urlencoded"
}

since header key is case-insentive, should we ignore case while evaluating header based condition?
@jeffreybozek - what do you think?

**Comment by jeffreybozek** [comment]
@rameshpolishetti The case handling will have to come from the trigger. The core mashling-activity runtime can be layered in with any trigger so we can't assume the behaviors of this trigger are universal. I would suggest using Go's default casing of the header keys or simply lowercasing everything. As long as it is documented with the trigger then users will know how exactly to access header values. The behavior appears to be handled here: https://github.com/golang/go/blob/master/src/net/textproto/reader.go#L564. So, "x-example-key" becomes "X-Example-Key".

**Comment by rameshpolishetti** [comment]
Since header key gets formatted by gorillamux trigger, use below condition to work as expected - 
"if": "payload.header.**Name** == 'test'"
