### ISSUE TITLE
Show warning message when config file contains ZERO triggers/handler/steps

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#169]
The gateway is starting even if the V2 mashling.json has empty Triggers, empty Handlers , No services or Empty steps in the routes in Dispatches.
No warning message is displayed to the user that the Trigger is missing.

Sample V2 Mashling.json:
`
{
  "mashling_schema": "1.0",
  "gateway": {
    "name": "MyProxy",
    "version": "1.0.0",
    "description": "This is a simple proxy.",
    "triggers": [],
    "dispatches": [
      {
        "name": "Pets",
        "routes": [
          {
            "steps": [],
            "responses": [
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) != 200",
                "error": true,
                "output": {
                  "code": 403,
                  "format": "json",
                  "body": "Pet is not available."
                }
              },
              {
                "if": "JSON.parse(FlogoRestGetFlow.response.outputs.code) == 200",
                "error": false,
                "output": {
                  "code": 200,
                  "format": "json",
                  "body": "${FlogoRestGetFlow.response.outputs.data}"
                }
              }
            ]
          }
        ]
      }
    ]
  }
}
`

**Comment by jeffreybozek** [comment]
This is addressed in PR #196.

**Comment by ykalidin** [comment]
Working Fine.
