### ISSUE TITLE
The mashling V2 binary created with mashling-cli.exe create command is generated outside the bin folder

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#172]
While creating app with mashling-cli.exe create command the binary is getting created in the mashling-custom folder outside the bin folder.

**Comment by jeffreybozek** [comment]
This was done by design so the executable would be at the top level of the folder and easy to find. After the binary is generated into the /release folder it is moved.

**Comment by rameshpolishetti** [comment]
On other note - should we delete src, pkg & bin folders so that user would have only useful mashling-gateway binary.

**Comment by rameshpolishetti** [comment]
Placing the generated binary mashling-gateway.exe under bin folder is not necessary. 
Not treating this an issue.
