### ISSUE TITLE
Environment variable are not getting resolved for service inputs in V2 model

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#174]
Environment variable are not getting resolved for service inputs in steps in V2 model.

`"service": "FlogoRestGetFlow",
                "input": {
                  "inputs.endPoint": "${env.URL}"
                }`

**Comment by rameshpolishetti** [comment]
@ykalidin PR 175 merged, now fix can be verified in feature-v2-model branch.

**Comment by LakshmiMekala** [comment]
Verified the env variable issue from master branch and observed that it is working fine
