### ISSUE TITLE
eventing for WebSockets

### ISSUE THREAD

**Issue by cchristodulis** [TIBCOSoftware/mashling#206]
As an API Consumer, I want to use a microgateway to open a WebSockets connection and parse data frames so that I can create events based on certain triggers/criteria.

Example:  Mashling is deployed to establish a WSS connection to a stream of log details, and when [X amount of failures are detected / Latency for requests increases above Y / ??] I want to create an event that [publishes a message / sends an email / triggers some action]

**Comment by rameshpolishetti** [comment]
PR #230 adds this feature.

**Comment by LakshmiMekala** [comment]
Verified websocket eventing and observed that it is working fine
