### ISSUE TITLE
go run build.go releaseall command is failing to generate release binaries

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/mashling#226]
go run build.go releaseall is failing with below error :
UPX not found, skipping compression (please visit https://upx.github.io to install)...
:arrow_forward: building release executables
panic: exit status 2: # github.com/TIBCOSoftware/[secure]/vendor/github.com/chewxy/math32
vendor/github.com/chewxy/math32/exp.go:3:6: missing function body
vendor/github.com/chewxy/math32/log.go:76:6: missing function body
vendor/github.com/chewxy/math32/remainder.go:33:6: missing function body
vendor/github.com/chewxy/math32/sqrt.go:3:6: missing function body
goroutine 1 [running]:
main.Resolve(0x4f3030)
   /home/travis/gopath/src/github.com/TIBCOSoftware/[secure]/build.go:102 +0x120
main.main()
   /home/travis/gopath/src/github.com/TIBCOSoftware/[secure]/build.go:225 +0x7c9
exit status 2

This issue is observed from PR #198

**Comment by pointlander** [comment]
Updating github.com/chewxy/math32 will probably fix this problem.

**Comment by LakshmiMekala** [comment]
Fixed with PR #227.

Verified and it is working fine
