### ISSUE TITLE
FATAL: command "create" failed: open vendor/src/github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger/trigger.json: no such file or directory

### ISSUE THREAD

**Issue by philippegabert** [TIBCOSoftware/mashling#75]
Hi, 

I am trying to play around with mashling and creating my app.

Basically, here is what I've done:

1. Brand new Ubuntu server machine
2. Install Go
3. Create a folder "go" in my home directory and create an environment variable "GOPATH" pointing to this directory
4. Installing GB tool
5. Adding $GOPATH/bin folder to the PATH environment variable 
6. Calling **mashling create myApp**

And... This does not work... I get this error message:

`FATAL: command "create" failed: open vendor/src/github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger/trigger.json: no such file or directory`

- Why is the "vendor" path added to the trigger.json path ?
- How can this be solved?

I am completely new to GO so maybe I miss something very obvious... Any help appreciated !

Thanks

**Comment by galois17** [comment]
That error can certain appear if GOPATH is not set correctly. I think you should first echo things out to rule it out:

% echo $GOPATH
<home_dir>/go
% which gb
<home_dir>/go/bin/gb

**Comment by philippegabert** [comment]
Hum hum... apparently there was an issue with my env variables for gb... (The which gb didn't return anything)

That seems alright now, I can create the app. Thanks !
