### ISSUE TITLE
mashling create myApp fails

### ISSUE THREAD

**Issue by yxuco** [TIBCOSoftware/mashling#95]
package references are broken.  see the following errors:

Getting golang.org/x/net/idna
fatal: https://go.googlesource.com/crypto/info/refs not valid: is this a git repository?
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
Getting golang.org/x/net/internal/timeseries
Getting golang.org/x/net/lex/httplex
Getting golang.org/x/net/trace
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
fatal: https://go.googlesource.com/net/info/refs not valid: is this a git repository?
Getting golang.org/x/sys/unix
fatal: https://go.googlesource.com/sys/info/refs not valid: is this a git repository?

**Comment by pointlander** [comment]
Pulling down the dependencies works for me (tested on linux and macOS). I would guess this is a network issue?

**Comment by yxuco** [comment]
I have connected to the internet and have access to other github resources. However, the above link on go.googleresource.com does not exist. All the failed packages are in fact at github.com/golang, which maybe why they failed.

**Comment by pointlander** [comment]
Perhaps a git compatibility issue? Which version of git do you have? (Also which computer platform are you using?) Thanks.

**Comment by pointlander** [comment]
On my systems git clone https://go.googlesource.com/net works with:
git version 2.14.3 (Apple Git-98)
git version 2.7.4
git version 2.1.4

**Comment by yxuco** [comment]
Got it working with the pre-installed git on my mac under /usr/bin, which is version 2.14.3 (Apple Git-98).  For some weird reason, other installed git version does not work on git clone https://go.googlesource.com.  This may not be an issue after all.  Thanks.

**Comment by yxuco** [comment]
See a different error when using "mashling create mashdemo":
........
github.com/lightstep/lightstep-tracer-go
FATAL: command "build" failed: exit status 2
Mashling gateway successfully built!

Then, tried to run "gb build" from the new project root folder, but got this:

/Users/yxu/Developer/go_workspace/mashdemo> gb build
# github.com/TIBCOSoftware/mashling/lib/util
util.go:74:18: cannot call non-function element.Name (type string)
FATAL: command "build" failed: exit status 2

**Comment by pointlander** [comment]
Yeah, that is fixed in the pull request: https://github.com/TIBCOSoftware/mashling/pull/96 Try building a recipe from: https://github.com/TIBCOSoftware/mashling-recipes Perhaps this recipe: https://github.com/TIBCOSoftware/mashling-recipes/tree/master/recipes/rest-conditional-gateway

**Comment by yxuco** [comment]
That works.  Thanks.

**Comment by pointlander** [comment]
A workaround for the primary git issue has been found. On Apple platforms the Apple build of git should be used. A pull request for the secondary issue has now been merged. The pull request updated the default manifest.
