### ISSUE TITLE
Mashling create myApp fails

### ISSUE THREAD

**Issue by mmussett** [TIBCOSoftware/mashling#97]
$ mashling create myApp
Getting github.com/TIBCOSoftware/flogo-cli/util
Getting github.com/NodePrime/jsonpath
Getting github.com/TIBCOSoftware/flogo-contrib/action/flow
Getting github.com/Sirupsen/logrus
Getting github.com/Shopify/sarama
Getting github.com/TIBCOSoftware/flogo-cli/env
Getting github.com/TIBCOSoftware/flogo-contrib/activity/reply
Getting github.com/TIBCOSoftware/flogo-contrib/activity/log
Getting github.com/TIBCOSoftware/flogo-contrib/activity/rest
Getting github.com/TIBCOSoftware/flogo-contrib/model/simple
Getting github.com/TIBCOSoftware/flogo-contrib/trigger/rest/cors
Getting github.com/TIBCOSoftware/flogo-lib
Getting github.com/TIBCOSoftware/mashling/ext/flogo/trigger/gorillamuxtrigger
Getting github.com/TIBCOSoftware/mashling/lib/conditions
Getting github.com/TIBCOSoftware/mashling/lib/util
Getting github.com/apache/thrift/lib/go/thrift
Getting github.com/davecgh/go-spew/spew
Getting github.com/eapache/go-resiliency/breaker
Getting github.com/eapache/go-xerial-snappy
Getting github.com/eapache/queue
Getting github.com/go-logfmt/logfmt
Getting github.com/gogo/protobuf/io
Getting github.com/gogo/protobuf/proto
Getting github.com/golang/protobuf/proto
Getting github.com/golang/protobuf/protoc-gen-go/descriptor
Getting github.com/golang/protobuf/ptypes
Getting github.com/golang/protobuf/ptypes/timestamp
Getting github.com/golang/snappy
Getting github.com/gorilla/mux
Getting github.com/japm/goScript
Getting github.com/julienschmidt/httprouter
Getting github.com/lightstep/lightstep-tracer-go
Getting github.com/opentracing-contrib/go-observer
Getting github.com/opentracing/basictracer-go
Getting github.com/opentracing/opentracing-go
Getting github.com/openzipkin/zipkin-go-opentracing
Getting github.com/pierrec/lz4
Getting github.com/pierrec/xxHash/xxHash32
Getting github.com/pkg/errors
Getting github.com/rcrowley/go-metrics
Getting golang.org/x/crypto/ssh/terminal
Getting golang.org/x/net/context
Getting golang.org/x/net/http2
Getting golang.org/x/net/idna
Getting golang.org/x/net/internal/timeseries
Getting golang.org/x/net/lex/httplex
Getting golang.org/x/net/trace
Getting golang.org/x/sys/unix
Getting golang.org/x/sys/windows
Getting golang.org/x/text/secure/bidirule
Getting golang.org/x/text/transform
Getting golang.org/x/text/unicode/bidi
Getting golang.org/x/text/unicode/norm
Getting google.golang.org/genproto/googleapis/api/annotations
Getting google.golang.org/genproto/googleapis/rpc/status
Getting google.golang.org/grpc
Getting sourcegraph.com/sourcegraph/appdash
FATAL: command "restore" failed: could not process dependency: go-import metadata not found
FATAL: command "vendor" failed: exit status 1
Generated mashling Artifacts.
Building mashling Artifacts.
/Users/markmussett/src/mashling/myApp
FATAL: command "build" failed: failed to resolve import path "myapp": import "sourcegraph.com/sourcegraph/appdash": not found: stat /Users/markmussett/src/mashling/myApp/src/sourcegraph.com/sourcegraph/appdash: no such file or directory

**Comment by pointlander** [comment]
I tested this on my machine and it worked, but the 'sourcegraph.com/sourcegraph/appdash' dependency was very slow to fetch. I suspect there is a problem with sourcegraph.com. Before trying again you will want to do a 'go get -u github.com/TIBCOSoftware/mashling/...'

**Comment by mmussett** [comment]
Did an update and create again and this time it worked.
I had previously done an update as my local version was a few weeks out-of-date so suspect it to slow repo causing the issue.

**Comment by pointlander** [comment]
The sourcegraph.com site is now working, so this issue has been fixed.
